<?php
//$nric = $_POST["NRIC"];
require('fpdf.php');
//echo $nric;
$sql = "SELECT * FROM attendance WHERE NRIC='$nric' ORDER BY `start`";
$_qry = mysqli_query($con, $sql);
$num = mysqli_num_rows($_qry);

$sql = "SELECT * FROM activestaff WHERE NRIC='$nric'";
$qry = mysqli_query($con, $sql);
$qry = mysqli_fetch_assoc($qry);

$staff = $qry["first_name"].' '.$qry["last_name"];
$mobile = $qry["mobile"];

class PDF extends FPDF
{
    // Page header
    function Header()
    {
        // Logo
        $this->Image('images/logo.png',10,6,30);
        // Arial bold 15
        $this->SetFont('Arial','B',15);
        // Move to the right
        $this->Cell(80);
        // Title
        $this->Cell(30,10,'Staff Attendance Report',0,0,'C');
        // Line break
        $this->Ln(20);
    }
    
    // Page footer
    function Footer()
    {
        // Position at 1.5 cm from bottom
        $this->SetY(-15);
        // Arial italic 8
        $this->SetFont('Arial','I',8);
        // Page number
        $this->Cell(0,10,'Iktihad Software',0,0,'C');
        $this->Cell(0,10,'Page '.$this->PageNo().'/{nb}',0,0,'C');
        
    }
    
    function ImprovedTable($header, $data)
    {
        // Column widths
        $w = array(40, 35, 40, 45);
        // Header
        for($i=0;$i<count($header);$i++)
            $this->Cell($w[$i],7,$header[$i],1,0,'C');
            $this->Ln();
            // Data
            foreach($data as $row)
            {
                $this->Cell($w[0],6,$row[0],'LR',0,'R');
                $this->Cell($w[1],6,$row[1],'LR',0,'R');
                $this->Cell($w[2],6,$row[2],'LR',0,'R');
                $this->Cell($w[3],6,$row[3],'LR',0,'R');
                //$this->Cell($w[2],6,number_format($row[2]),'LR',0,'R');
                //$this->Cell($w[3],6,number_format($row[3]),'LR',0,'R');
                $this->Ln();
            }
            // Closing line
            $this->Cell(array_sum($w),0,'','T');
    }
    
}

// Instanciation of inherited class
$pdf = new PDF();

$header = array('Day, Date', 'Start', 'Stop', 'Note');
$data = array();

$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->SetFont('Times','',12);
$pdf->Cell(0,10,'Staff Name : '.$staff,0,1);
$pdf->Cell(0,10,'NRIC Code : '.$nric,0,1);
$pdf->Cell(0,10,'Contact : +'.$mobile,0,1);
$pdf->Ln();

$workHour = 0;
while($row = mysqli_fetch_assoc($_qry)){
    $data[] = array(date("l, d M", $row["start"]),date("G:i:s",$row["start"]),date("G:i:s",$row["end"]),$row["note"]);
    $workHour += ($row["end"] - $row["start"]);
}
$workHour = $workHour / 60 / 60;
    $pdf->ImprovedTable($header,$data);
  
$pdf->Ln();
$pdf->Cell(0,10,'Total Work Hour is : '.round($workHour, 2).' hour(s)',0,1);
$pdf->Cell(0,10,'This report is generated by computer',0,1);

// email stuff (change data below)
//$to = "adibbazli1@gmail.com";
$to = $qry["email"];
$from = "limemalaysia@gmail.com";
$subject = "Your Attendance Report";
$message = "<p>Dear <b>$staff</b>,</p><p>This email was sent at your request.</p><p>Please see the attachment.</p>";

// a random hash will be necessary to send mixed content
$separator = md5(time());

// carriage return type (we use a PHP end of line constant)
$eol = PHP_EOL;

$pdfdoc = $pdf->Output("", "S");
$attachment = chunk_split(base64_encode($pdfdoc));

$filename = date("dmy", time()).'.pdf';

// main header
$headers  = "From: ".$from.$eol;
$headers .= "MIME-Version: 1.0".$eol;
$headers .= "Content-Type: multipart/mixed; boundary=\"".$separator."\"";

// no more headers after this, we start the body! //

$body = "--".$separator.$eol;
$body .= "Content-Transfer-Encoding: 7bit".$eol.$eol;
$body .= "".$eol;

// message
$body .= "--".$separator.$eol;
$body .= "Content-Type: text/html; charset=\"iso-8859-1\"".$eol;
$body .= "Content-Transfer-Encoding: 8bit".$eol.$eol;
$body .= $message.$eol;

// attachment
$body .= "--".$separator.$eol;
$body .= "Content-Type: application/octet-stream; name=\"".$filename."\"".$eol;
$body .= "Content-Transfer-Encoding: base64".$eol;
$body .= "Content-Disposition: attachment".$eol.$eol;
$body .= $attachment.$eol;
$body .= "--".$separator."--";

// send message
mail($to, $subject, $body, $headers);
?>